import { X, Download } from 'lucide-react';
import { type Artifact } from '../data/mockData';

function getPreviewDetails(artifact: Artifact) {
  let bgClass = 'bg-[#1e293b]';
  let accentClass = 'bg-[#94a3b8]';
  let textAccent = 'text-[#94a3b8]';

  if (artifact.type === 'PDF') {
    bgClass = 'bg-[#7f1d1d]';
    accentClass = 'bg-[#f87171]';
    textAccent = 'text-[#f87171]';
  } else if (artifact.type === 'RPT') {
    bgClass = 'bg-[#312e81]';
    accentClass = 'bg-[#818cf8]';
    textAccent = 'text-[#818cf8]';
  } else if (artifact.type === 'DOC') {
    bgClass = 'bg-[#1e3a8a]';
    accentClass = 'bg-[#60a5fa]';
    textAccent = 'text-[#60a5fa]';
  } else if (artifact.type === 'CSV') {
    bgClass = 'bg-[#14532d]';
    accentClass = 'bg-[#4ade80]';
    textAccent = 'text-[#4ade80]';
  }

  return { bgClass, accentClass, textAccent };
}

const getMockFileContent = (artifact: Artifact) => {
  return `RESEARCH ARTIFACT: ${artifact.title}
Date: ${artifact.generatedDate}
Type: ${artifact.type}
Metadata: ${artifact.metadata}

[GENERATED CONTENT]
This is a demonstration file representing the artifact generated by your AI Research Assistant.
In a real environment, this would be a precisely formatted ${artifact.type} file containing your analysis, guides, or data exports.`;
};

// Mock presentation slide for PDF artifacts
function MockPdfPresentationView({ title }: { title: string }) {
  return (
    <div className="flex h-full w-full flex-col items-center justify-center bg-gradient-to-br from-[#7f1d1d] via-[#450a0a] to-[#2e1065] p-6 text-center border border-red-900 pointer-events-none rounded-[14px] overflow-hidden relative">
      <div className="absolute top-4 left-6 text-red-200/40 font-bold text-[10px] tracking-[0.2em] uppercase">Generated Deck</div>
      
      <div className="w-12 h-1 bg-red-400 mb-6 rounded-full opacity-80"></div>
      
      <h1 className="text-[22px] font-bold text-white mb-4 px-8 leading-tight drop-shadow-lg">
        {title}
      </h1>
      <p className="text-red-200 text-xs tracking-wide max-w-[80%] opacity-80 font-light">
        Custom Discovery Guide · System Generated
      </p>
      
      <div className="absolute bottom-4 left-1/2 -translate-x-1/2 flex items-center gap-1.5 opacity-30">
        <div className="w-1 h-1 rounded-full bg-white"></div>
        <div className="w-1 h-1 rounded-full bg-white/40"></div>
        <div className="w-1 h-1 rounded-full bg-white/40"></div>
      </div>
    </div>
  );
}

export default function ArtifactPreviewModal({ 
  artifact, 
  onClose 
}: { 
  artifact: Artifact; 
  onClose: () => void 
}) {
  const details = getPreviewDetails(artifact);

  const handleDownload = () => {
    const element = document.createElement("a");
    const fileContent = getMockFileContent(artifact);
    const blob = new Blob([fileContent], { type: 'text/plain' });
    
    element.href = URL.createObjectURL(blob);
    // Append a mock extension
    let ext = '.txt';
    if (artifact.type === 'CSV') ext = '.csv';
    
    const downloadName = artifact.title.replace(/\s+/g, '_') + ext;
    element.download = downloadName;
    
    document.body.appendChild(element);
    element.click();
    document.body.removeChild(element);
    
    setTimeout(() => URL.revokeObjectURL(element.href), 100);
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 backdrop-blur-sm px-4">
      <div className="relative flex w-full max-w-[600px] flex-col rounded-[20px] bg-white p-6 shadow-2xl">
        <button 
          onClick={onClose}
          className="absolute right-4 top-4 rounded-md p-1.5 text-text-tertiary transition-colors z-10 hover:bg-surface-secondary hover:text-text-primary cursor-pointer"
        >
          <X size={24} strokeWidth={1.5} />
        </button>
        
        <h2 className="mb-8 mr-8 text-[22px] font-semibold text-gray-900 leading-tight">
          {artifact.title}
        </h2>
        
        <div 
          onClick={handleDownload}
          className={`group relative mx-auto flex w-full cursor-pointer flex-col items-center justify-center rounded-xl border-[3px] border-transparent transition-all hover:border-primary-500 hover:shadow-xl p-1 ${artifact.type === 'PDF' ? 'aspect-[16/9] max-w-[560px]' : 'aspect-[4/2.6] max-w-[480px]'}`}
          title="Click to download artifact"
        >
          {/* Stacked cards effect for "multiple pages" */}
          <div className="relative w-full h-full">
            {/* Background page 2 */}
            <div className="absolute right-1 top-2 h-full w-[calc(100%-8px)] rounded-xl bg-gray-50 shadow-sm border border-gray-100"></div>
            {/* Background page 1 */}
            <div className="absolute right-2 top-4 h-full w-[calc(100%-16px)] rounded-xl bg-gray-100 shadow-sm border border-gray-200/60"></div>
            
            {/* Main Cover Card */}
            <div className={`absolute left-0 right-4 top-6 h-[calc(100%-24px)] flex flex-col justify-center rounded-[14px] ${artifact.type === 'PDF' ? 'bg-white' : details.bgClass} ${artifact.type !== 'PDF' ? 'p-8' : ''} text-white shadow-md transition-transform group-hover:-translate-y-1 overflow-hidden`}>
              
              {artifact.type !== 'PDF' && (
                <>
                  {/* Left accent border */}
                  <div className={`absolute left-0 top-0 h-full w-2.5 rounded-l-xl ${details.accentClass}`}></div>
                  
                  <div className="pl-6 pt-2">
                    <h3 className="mb-2 text-[26px] font-bold tracking-tight text-white leading-tight">
                      {artifact.title}
                    </h3>
                    <p className={`mb-8 text-sm font-medium ${details.textAccent}`}>
                      System Generated {artifact.type}
                    </p>
                    
                    <div className="mt-auto space-y-2 text-[11px] font-medium text-white/50">
                      <p>Details: {artifact.metadata}</p>
                      <p>Status: {artifact.generatedDate}</p>
                    </div>
                  </div>
                </>
              )}

              {artifact.type === 'PDF' && (
                <MockPdfPresentationView title={artifact.title} />
              )}

              {/* Download overlay icon on hover */}
              <div className="absolute inset-0 flex items-center justify-center rounded-[14px] bg-black/0 transition-colors group-hover:bg-black/40">
                <div className="flex flex-col h-20 w-20 items-center justify-center rounded-full bg-primary-600 text-white opacity-0 shadow-2xl transition-all group-hover:opacity-100 group-hover:scale-110">
                  <Download size={32} />
                </div>
              </div>
            </div>
          </div>
          
          <div className="mt-8 flex items-center justify-center bg-white px-6 py-2 block text-center">
            <span className="text-[15px] font-medium text-gray-800">
              {artifact.metadata.split(' · ')[0] || 'Generated Output'}
            </span>
          </div>
        </div>
      </div>
    </div>
  );
}
